### ISSUE TITLE
Is streaming output supported?

### ISSUE THREAD

**Issue by iamarmanjon** [busyloop/net-ssh-simple#5]
I was using Net::SSH before but I have a hard time streaming the output, example I'm doing a `apt-get install package`, I want to stream the output, not show it after the process is done. Do you have a wrapper for it, maybe I haven't looked at the docs well :)

**Comment by m-o-e** [comment]
Yes, streaming is supported through an event API, see the last example on this page: http://busyloop.github.io/net-ssh-simple/doc/Net/SSH/Simple.html ("Here be dragons").

**Comment by iamarmanjon** [comment]
thanks!
